#
- include: packages.yml
#
- name: Install and configure db
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel
    - python-psycopg2
#
- name: Run initdb command
  raw: postgresql-setup initdb
  become: yes

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user: db={{ app_name }}
                                name={{ db_user }}
                                password={{ db_password }}
                                priv=ALL
                                role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres

- name: Creates virtualenvs directory
  file:
    path: /home/{{deployer_user}}/.virtualenvs
    state: directory

- name: Change deploydir owner
  file:
    path: "{{ app_dir }}"
    owner: "{{ deployer_user }}"
    state: directory
  become: yes


- name: Clone or pull the latest code
  git: repo={{ code_repository_url }}
        dest={{ app_dir }} accept_hostkey=yes
  notify:
    - collect static files
    - migrate db
    - install requirements

 #configuring web server
- name: Write nginx conf file
  template: src=example-django-nginx.conf dest=/etc/nginx/sites-available/{{ app_name }}
  become: yes
- name: Creates sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{app_name}}
    path: /etc/nginx/sites-enabled/{{app_name}}
    state: link
  become: yes
  notify:
    - restart nginx
    -
- name: Creates directory
  file:
    path: /var/{{app_name}}/media
    state: directory
  become: yes

# configuring supervisor
- name: Write supervisor conf file
  template: src=example-django-supervisor.conf dest=/etc/supervisor/conf.d/{{ app_name }}.conf
  notify: reread supervisor