
- name: installing core packages
  become: yes
  apt:
    name:
      - rsync
      - sudo
      - supervisor
      - git
      - python-pip
      - python-dev
      - python3-pip
      - virtualenv
      - python-psycopg2
      - libsqlite3-dev
      - python3-dev
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - nginx
      - build-essential
      - axel
      - acl #enable to enable access to tmp files for non-root users
    state: present

    autoclean: yes
