# Generated by Django 2.2.1 on 2019-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='type',
            field=models.CharField(default='Sedan', max_length=20),
            preserve_default=False,
        ),
    ]
