# Generated by Django 2.2.1 on 2019-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('eco', 'Economic'), ('buss', 'Business'), ('first', 'First class')], max_length=10),
        ),
    ]
