# Generated by Django 2.2.1 on 2019-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190510_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='hybrid_or_electric',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, choices=[('eco', 'Economic'), ('buss', 'Business'), ('first', 'First class')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='hybrid_or_electric',
            field=models.BooleanField(default=False),
        ),
    ]
