# Generated by Django 2.2.1 on 2019-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190510_1347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('name', 'producer', 'type')},
        ),
    ]
